### ISSUE TITLE
`remind config` not working

### ISSUE THREAD

**Issue by eliasbagley** [zeke/remind-me#56]
I'm getting the following error in version 1.6.0:

My permissions for config.json are: `-rw-r--r--  1 eliasbagley  staff  358 Mar 29 07:58 /Users/eliasbagley/.remind-me/config.json`

```
/bin/sh: /Users/eliasbagley/.remind-me/config.json: Permission denied
child_process.js:512
    throw err;
    ^

Error: Command failed: $EDITOR ~/.remind-me/config.json
/bin/sh: /Users/eliasbagley/.remind-me/config.json: Permission denied

    at checkExecSyncError (child_process.js:469:13)
    at execSync (child_process.js:509:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/remind-me/index.js:41:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by zeke** [comment]
Thanks for reporting,  @eliasbagley. I'll try to dig into that soon.
