### ISSUE TITLE
installation error: "TypeError: Path must be a string. Received <Buffer..."

### ISSUE THREAD

**Issue by katylava** [zeke/remind-me#61]
```
> remind-me@1.6.0 setup /usr/local/lib/node_modules/remind-me
> node ./lib/setup.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received <Buffer 2f 75 73 72 2f 6c 6f 63 61 6c 2f 43 65 6c 6c 61 72 2f 6e 6f 64 65 36 2d 6c 74 73 2f 36 2e 39 2e 31 2f 62 69 6e 2f 6e 6f 64 65 0a>
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /usr/local/lib/node_modules/remind-me/lib/setup.js:37:22
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/remind-me/node_modules/crontab/lib/index.js:336:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

running node version 6.9.1 and npm version 3.10.8

**Comment by zeke** [comment]
Sorry @katylava, but this project is unmaintained.

The best alternative I can recommend at the moment is Slack's `/remind` feature: https://get.slack.help/hc/en-us/articles/208423427-Set-a-reminder
