### ISSUE TITLE
Can't install NPM package on c9.com

### ISSUE THREAD

**Issue by DaniyalGeek** [zeke/remind-me#64]
bitnary:~/workspace $ sudo npm i -g remind-me                                                                                            
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/home/ubuntu/.nvm/versions/node/v6.11.2/bin/remind -> /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me/index.js
/home/ubuntu/.nvm/versions/node/v6.11.2/bin/remind-me -> /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me/index.js

> remind-me@1.6.1 postinstall /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me
> npm run setup

> remind-me@1.6.1 setup /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me
> node ./lib/setup.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received <Buffer 2f 68 6f 6d 65 2f 75 62 75 6e 74 75 2f 2e 6e 76 6d 2f 76 65 72 73 69 6f 6e 73 2f 6e 6f 64 65 2f 76 36 2e 31 31 2e 32 2f 62 69 6e 2f 6e 6f 64 65 0a>
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me/lib/setup.js:37:22
    at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me/node_modules/crontab/lib/index.js:358:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

npm ERR! Linux 4.9.80-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "run" "setup"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! remind-me@1.6.1 setup: `node ./lib/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remind-me@1.6.1 setup script 'node ./lib/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remind-me package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remind-me
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remind-me
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/remind-me/npm-debug.log
/home/ubuntu/.nvm/versions/node/v6.11.2/lib
└── (empty)

npm ERR! Linux 4.9.80-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "i" "-g" "remind-me"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! remind-me@1.6.1 postinstall: `npm run setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remind-me@1.6.1 postinstall script 'npm run setup'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remind-me package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run setup
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remind-me
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remind-me
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
npm ERR! code 1

**Comment by zeke** [comment]
Hi there. Unfortunately I do not have the time to maintain this project. Good luck!
